name: Automatic Release on Push
on: [push]
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate .love file
        run: zip -9 -r thefbird.love . -x '*.git*' -x '*.vscode*' -x '*.github*'
      - uses: suisei-cn/actions-download-file@v1
        id: lovebins
        name: Download Love2D Binaries for windows
        with:
          url: "https://github.com/love2d/love/releases/download/11.3/love-11.3-win64.zip"                
      - name: Generating Binaries for windows
        run: |
          unzip love-11.3-win64
          mv thefbird.love love-11.3-win64
          cat love-11.3-win64/love.exe love-11.3-win64/thefbird.love > love-11.3-win64/thefbird.exe
          mv love-11.3-win64/ win64/
          rm -rf win64/*.ico
          rm -rf win64/lov*.exe          
          rm -rf win64/*.ico      
          rm -rf win64/*.love
      - name: Archive binaries for windows
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.ref }}-win64
          path: win64
          retention-days: 5