name: Automatic Release on Push
on:
  push:
    branches:
      - "main"
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'      
      - name: Generate .love file
        run: zip -9 -r thefbird.love . -x '*.git*' -x '*.vscode*' -x '*.github*'
      - uses: suisei-cn/actions-download-file@v1
        id: lovebinswin64
        name: Download Love2D Binaries for windows
        with:
          url: "https://github.com/love2d/love/releases/download/11.3/love-11.3-win64.zip"                
      - name: Generating Binaries for win64
        run: |
          unzip love-11.3-win64
          cp thefbird.love love-11.3-win64
          cat love-11.3-win64/love.exe love-11.3-win64/thefbird.love > love-11.3-win64/thefbird.exe
          mv love-11.3-win64/ win64/
          rm -rf win64/*.ico
          rm -rf win64/lov*.exe          
          rm -rf win64/*.ico      
          rm -rf win64/*.love
      - uses: suisei-cn/actions-download-file@v1
        id: lovebinsmacos
        name: Download Love2D Binaries for mac
        with:
          url: "https://github.com/love2d/love/releases/download/11.3/love-11.3-macos.zip"                
      - name: Generating Binaries for macos
        run: |
          unzip love-11.3-macos
          mv love.app thefbird.app
          cp thefbird.love thefbird.app/Contents/Resources/thefbird.love
          sed -i 's/<string>org\.love2d\.love<\/string>/<string>io\.github\.paulushcgcj\.thefbird<\/string>/' thefbird.app/Contents/Info.plist
          sed -i 's/<string>LÖVE<\/string>/<string>Filphy Bird by Paulo<\/string>/' thefbird.app/Contents/Info.plist
          head -n 103 thefbird.app/Contents/Info.plist >> thefbird.app/Contents/Info.plist.bkp
          tail -n 2 thefbird.app/Contents/Info.plist >> thefbird.app/Contents/Info.plist.bkp
          rm -rf thefbird.app/Contents/Info.plist
          mv thefbird.app/Contents/Info.plist.bkp thefbird.app/Contents/Info.plist
          zip -r -y thefbird.dmg thefbird.app
      - name: Bump version and push tag
        id: tag_bump
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: main
          INITIAL_VERSION: 1.0.0
          WITH_V: true
      - name: Preparing Files to Upload
        run: |
            zip -r -y -9 thefbird-${{ steps.tag_bump.outputs.new_tag }}-win64.zip win64/
            mv thefbird.dmg thefbird-${{ steps.tag_bump.outputs.new_tag }}.dmg
            mv thefbird.love thefbird-${{ steps.tag_bump.outputs.new_tag }}.love
      - uses: meeDamian/github-release@2.0
        name: Updating Release with artifact
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.tag_bump.outputs.new_tag }}
          files: >            
            thefbird-${{ steps.tag_bump.outputs.new_tag }}-win64.zip
            thefbird-${{ steps.tag_bump.outputs.new_tag }}.dmg
            thefbird-${{ steps.tag_bump.outputs.new_tag }}.love
